### ISSUE TITLE
Fails to decode Float/Decimal with exponent notation

### ISSUE THREAD

**Issue by Selvaticus** [beam-community/avro_ex#18]
Hi,

I believe I'm having an issue when the lib tries to decode a float like this `2.56238833228314e-39`.

When calling `AvroEx.Decode.decode(schema, avro_binary)` get this error:
```sh
** (FunctionClauseError) no function clause matching in :lists.nth/2    
    
    The following arguments were given to :lists.nth/2:
    
        # 1
        -39
    
        # 2
        [
          %AvroEx.Schema.Primitive{metadata: %{}, type: nil},
          %AvroEx.Schema.Primitive{metadata: %{}, type: :double}
        ]
    
    (stdlib) lists.erl:170: :lists.nth/2
    (avro_ex) lib/avro_ex/decode.ex:162: AvroEx.Decode.do_decode/3
    (avro_ex) lib/avro_ex/decode.ex:139: anonymous fn/3 in AvroEx.Decode.do_decode/3
    (elixir) lib/enum.ex:1940: Enum."-reduce/3-lists^foldl/2-0-"/3
    (avro_ex) lib/avro_ex/decode.ex:138: AvroEx.Decode.do_decode/3
    (avro_ex) lib/avro_ex/decode.ex:11: AvroEx.Decode.decode/2
```

I believe this is the bit causing the issue (as I don't have `-39` on its own anywhere else in the file):
```json
{
...
    "additional": 2.56238833228314e-39,
...
}
```

**Comment by doomspork** [comment]
Thanks for the report @Selvaticus! Would you be inclined to submit a PR to resolve this issue? Anyone on the @beam-community/avroex team would be happy to help you with reviews 😁

**Comment by Selvaticus** [comment]
@doomspork I'll give it a go in my spare time.

Might not be a problem (or at least not with the decode bit), as I believe the file I was decoding is a `Object Container Files`, not sure if it changes anything.

Also, I'm sure what to expect of the precision of float/double values in avro.

**Comment by davydog187** [comment]
I am unable to reproduce

```elixir
iex(12)> float = 2.56238833228314e-39
2.56238833228314e-39
iex(13)> schema = AvroEx.parse_schema!(~S(["null", "float"]))
%AvroEx.Schema{
  context: %AvroEx.Schema.Context{names: %{}},
  schema: %AvroEx.Schema.Union{
    possibilities: [
      %AvroEx.Schema.Primitive{metadata: %{}, type: nil},
      %AvroEx.Schema.Primitive{metadata: %{}, type: :float}
    ]
  }
}
iex(14)> {:ok, encoded} = AvroEx.encode(schema, float)
{:ok, <<2, 229, 230, 27, 0>>}
iex(15)> AvroEx.decode(schema, encoded)
{:ok, 2.5623877471935383e-39}
```

@Selvaticus please reopen if you experience again
