### ISSUE TITLE
Property test failure

### ISSUE THREAD

**Issue by davydog187** [beam-community/avro_ex#78]
https://github.com/beam-community/avro_ex/runs/7027232352?check_suite_focus=true

```elixir
1) test encoding of large integer as a union of int and long (AvroEx.PropertyTest)
Error:      test/property_test.exs:5
     ** (MatchError) no match of right hand side value: false
     code: assert {:ok, ^data} = AvroEx.decode(schema, encoded)
     stacktrace:
       (avro_ex 2.0.1) lib/avro_ex/decode.ex:254: AvroEx.Decode.variable_integer_decode/4
Warning:        (avro_ex 2.0.1) lib/avro_ex/decode.ex:68: AvroEx.Decode.do_decode/4
       (avro_ex 2.0.1) lib/avro_ex/decode.ex:189: AvroEx.Decode.do_decode/4
Warning:        (avro_ex 2.0.1) lib/avro_ex/decode.ex:[19](https://github.com/beam-community/avro_ex/runs/7027232352?check_suite_focus=true#step:6:20): AvroEx.Decode.decode/3
       (avro_ex 2.0.1) lib/avro_ex.ex:176: AvroEx.decode/3
Warning:        test/property_test.exs:13: (test)
```

**Comment by davydog187** [comment]
Also see https://github.com/beam-community/avro_ex/pull/80#issuecomment-1207836026
